import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import BootstrapIcon from "@dvuckovic/vue3-bootstrap-icons";
import axios from "axios";
window.axios = axios;
const app = createApp(App);
app.use(store).use(router);
app.component("bi", BootstrapIcon);
app.mount("#app");
